version: '3'
services:
  mediamtx:
    # image: bluenviron/mediamtx:latest-ffmpeg-rpi
    image: bluenviron/mediamtx:latest
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=`ip addr show | grep "scope global wlan0" | awk '{print $2}' | cut -d/ -f1`
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    restart: unless-stopped
